import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import { NextAuthProvider } from '@/app/components/Provider';
import { authOptions } from '@/app/lib/auth';
import { getServerSession } from 'next-auth';
import {Logout, NavLogin} from "@/app/components/Button";
import Image from "next/image";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'ChikChat',
  description: 'Generated by create next app',
};

// This is server function. so can use async function
export default async function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang='en'>
      <body className={inter.className}>
        <NextAuthProvider>
          <nav className='flex px-10 py-5 justify-between fixed top-0 left-0 w-full bg-white'>
            <h1 className='text-black text-3xl font-bold'>
              Chik<span className='text-teal-500'>Chat</span>
            </h1>


            {session ? (
                <div className="flex items-center">
                  <Image
                      src={session.user?.image as string}
                      alt="user profile photo"
                      className="w-12 h-12 rounded-full mr-3"
                      width={50}
                      height={50}
                  />
                  <Logout />
                </div>
            ) : (
                <NavLogin />
            )}
          </nav>
          <main>{children}</main>
        </NextAuthProvider>
      </body>
    </html>
  );
}
